### ISSUE TITLE
ActionView::Template::Error (undefined method `edit_query_path'

### ISSUE THREAD

**Issue by wzymaster** [esminc/adhoq#122]
When saving a query ,I get error like  : 

```
ActionView::Template::Error (undefined method `edit_query_path' for #<#<Class:0x007fa55c348470>:0x007fa564738140>):
    3:     h1
    4:       = query.name
    5:       .pull-right
    6:         = link_to [:edit, query], class: 'btn btn-default btn-sm' do
    7:           i.fa.fa-pencil.fa-pad-r
    8:           | Edit
    9:       .pull-right

actionpack (5.0.0.1) lib/action_dispatch/routing/polymorphic_routes.rb:216:in `polymorphic_method'
actionpack (5.0.0.1) lib/action_dispatch/routing/polymorphic_routes.rb:130:in `polymorphic_path'
actionview (5.0.0.1) lib/action_view/routing_url_for.rb:102:in `url_for'
actionview (5.0.0.1) lib/action_view/helpers/url_helper.rb:196:in `link_to'
```

**Comment by takkanm** [comment]
It could not be reproduced by my environment.
Does include edit_query path in result of rake routes?

following log is my application. (Rails5.0.0.1)
```
$ be rake routes | grep query
query_executions POST   /q/:query_id/executions(.:format)     adhoq/executions#create
query_execution GET    /q/:query_id/executions/:id(.:format) adhoq/executions#show
edit_query GET    /q/:id/edit(.:format)                 adhoq/queries#edit
query GET    /q/:id(.:format)                      adhoq/queries#show
```

**Comment by hanachin** [comment]
I've got same error on my API only mode application.

The API-only modes is application wide config.
https://github.com/rails/rails/issues/24264#issuecomment-218218511

It affects to default_actions, `edit` and `new` routes are not defined in API only app.
https://github.com/rails/rails/blob/v5.1.1/actionpack/lib/action_dispatch/routing/mapper.rb#L1128,L1134

Here is the reproduce code:

```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "rails", "5.1.1"
  gem "adhoq"
  gem "sqlite3"
end

require "rack/test"
require "action_controller/railtie"
require "active_record/railtie"
require "adhoq"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  # NOTE commented out to pass the test
  config.api_only = true

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

TestApp.initialize!

class ApplicationController < ActionController::Base; end

TestApp.routes.draw do
  mount Adhoq::Engine => '/adhoq'
end

require "minitest/autorun"

ActiveRecord::Schema.define do

  create_table "adhoq_executions", force: :cascade do |t|
    t.integer  "query_id",                            null: false
    t.text     "raw_sql",                             null: false
    t.string   "report_format",                       null: false
    t.string   "status",        default: "requested", null: false
    t.text     "log"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
  end

  create_table "adhoq_queries", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.text     "query"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  create_table "adhoq_reports", force: :cascade do |t|
    t.integer  "execution_id", null: false
    t.string   "identifier",   null: false
    t.time     "generated_at", null: false
    t.string   "storage",      null: false
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
  end

  add_index "adhoq_reports", ["execution_id"], name: "index_adhoq_reports_on_execution_id"

  create_table "no_id_tables", id: false, force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "secret_tables", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def setup
    Adhoq::Query.create!(
      name:        'A query',
      description: 'Simple simple SELECT',
      query:       'SELECT 1'
    )
  end

  def test_returns_success
    get "/adhoq/q"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by takkanm** [comment]
@wzymaster @hanachin It will fixt. https://github.com/esminc/adhoq/pull/142
I passed hanachin's reproduce code.

**Comment by takkanm** [comment]
#142 merged.

**Comment by hanachin** [comment]
I tried master branch after #142 merged, the edit_path error fixed in my environment! thank you <3
